[package]
name = "matching_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
rand = "0.8"

[profile.release]
lto = true
codegen-units = 1

[[bin]]
name = "bench"
path = "src/bin/bench.rs"
